title: DongsuLee
description: >- # this means to ignore newlines until "baseurl:"
  AI, Reinforcement Learning, Cognitive Neuroscience, Bioinformatics
og_image: /assets/img/home/Profile.jpg
google_analytics: "G-9HTVQTM2EW"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
#    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: movementwater@soongsil.ac.kr
      link: mailto:movementwater@soongsil.ac.kr
#    - name: WeChat
#      value: YourWeChatUsername
#      link: "#"
  follow:
#    - name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"
#    - name: Facebook
#      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://www.linkedin.com/in/dongsulee/
    - name: GitHub
      link: http://github.com/LeeXim
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - name: RSS
#      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

remote_theme : eliottvincent/bay

url : "https://LeeXim.github.io"
baseurl : ""

# Analytics
# analytics:
#   provider               : "google-gtag"
                          # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          : "G-9HTVQTM2EW"
#     anonymize_ip         : # true, false (default)
